"""fix user job relationships

Revision ID: 88731d15ba05
Revises: 041852c76f7c
Create Date: 2026-01-31 11:01:45.256807

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '88731d15ba05'
down_revision: Union[str, Sequence[str], None] = '041852c76f7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'jobs', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')  # pyright: ignore[reportArgumentType]
    # ### end Alembic commands ###
